/**
 * Data Connectivity Management API
 * Use the Data Connectivity Management Service APIs to perform common extract, load, and transform (ETL) tasks.
 * OpenAPI spec version: 20210217
 * Contact: di_dcms_dev_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * The request object for single derived Entity.
 */
export interface DeriveEntitiesItem {
  /**
   * The model type of DeriveEntitiesRequestItem
   */
  "modelType": string;
  /**
   * Determines whether derived entity is treated as source or target
   */
  "mode": DeriveEntitiesItem.Mode;
  "referencedDataObject":
    | model.ReferencedDataObjectFromAPI
    | model.ReferencedDataObjectFromProcedure;
}

export namespace DeriveEntitiesItem {
  export enum Mode {
    In = "IN",
    Out = "OUT"
  }

  export function getJsonObj(obj: DeriveEntitiesItem): object {
    const jsonObj = {
      ...obj,
      ...{
        "referencedDataObject": obj.referencedDataObject
          ? model.ReferencedDataObject.getJsonObj(obj.referencedDataObject)
          : undefined
      }
    };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: DeriveEntitiesItem): object {
    const jsonObj = {
      ...obj,
      ...{
        "referencedDataObject": obj.referencedDataObject
          ? model.ReferencedDataObject.getDeserializedJsonObj(obj.referencedDataObject)
          : undefined
      }
    };

    return jsonObj;
  }
}
