/**
 * Fleet Application Management Service API
 * Fleet Application Management Service API. Use this API to for all FAMS related activities.
To manage fleets,view complaince report for the Fleet,scedule patches and other lifecycle activities

 * OpenAPI spec version: 20230831
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as requests from "./lib/request";
import * as models from "./lib/model";
import * as responses from "./lib/response";
import * as client from "./lib/client";
import * as fleetappsmanagement_waiter from "./lib/fleetappsmanagement-waiter";
import * as fleetappsmanagementadmin_waiter from "./lib/fleetappsmanagementadmin-waiter";
import * as fleetappsmanagementmaintenancewindow_waiter from "./lib/fleetappsmanagementmaintenancewindow-waiter";
import * as fleetappsmanagementoperations_waiter from "./lib/fleetappsmanagementoperations-waiter";
import * as fleetappsmanagementrunbooks_waiter from "./lib/fleetappsmanagementrunbooks-waiter";

export { models };
export { requests };
export { responses };
export import FleetAppsManagementClient = client.FleetAppsManagementClient;
export import FleetAppsManagementWaiter = fleetappsmanagement_waiter.FleetAppsManagementWaiter;
export import FleetAppsManagementAdminClient = client.FleetAppsManagementAdminClient;
export import FleetAppsManagementAdminWaiter = fleetappsmanagementadmin_waiter.FleetAppsManagementAdminWaiter;
export import FleetAppsManagementMaintenanceWindowClient = client.FleetAppsManagementMaintenanceWindowClient;
export import FleetAppsManagementMaintenanceWindowWaiter = fleetappsmanagementmaintenancewindow_waiter.FleetAppsManagementMaintenanceWindowWaiter;
export import FleetAppsManagementOperationsClient = client.FleetAppsManagementOperationsClient;
export import FleetAppsManagementOperationsWaiter = fleetappsmanagementoperations_waiter.FleetAppsManagementOperationsWaiter;
export import FleetAppsManagementRunbooksClient = client.FleetAppsManagementRunbooksClient;
export import FleetAppsManagementRunbooksWaiter = fleetappsmanagementrunbooks_waiter.FleetAppsManagementRunbooksWaiter;
