/**
 * Fleet Application Management Service API
 * Fleet Application Management provides a centralized platform to help you automate resource management tasks, validate patch compliance, and enhance operational efficiency across an enterprise.

 * OpenAPI spec version: 20250228
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Depends on object.
 */
export interface KmsSecretVariableDependsOn {
  /**
   * OCID of the compartment.
   */
  "compartmentId": string;
  /**
   * OCID of the Vault.
   */
  "vaultId"?: string;
  /**
   * Name of the KMS secret in the vault.
   */
  "name"?: string;
}

export namespace KmsSecretVariableDependsOn {
  export function getJsonObj(obj: KmsSecretVariableDependsOn): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: KmsSecretVariableDependsOn): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
}
