/**
 * Fleet Application Management Service API
 * Fleet Application Management provides a centralized platform to help you automate resource management tasks, validate patch compliance, and enhance operational efficiency across an enterprise.

 * OpenAPI spec version: 20250228
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * The details of the output variable that will be used for mapping.
 */
export interface OutputVariableDetails {
  /**
   * The name of the task step the output variable belongs to.
   */
  "stepName": string;
  /**
   * The name of the output variable whose value has to be mapped.
   */
  "outputVariableName": string;
}

export namespace OutputVariableDetails {
  export function getJsonObj(obj: OutputVariableDetails): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: OutputVariableDetails): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
}
