/**
 * MarketplacePublisherService API
 * Use the Marketplace Publisher API to manage the publishing of applications in Oracle Cloud Infrastructure Marketplace.
 * OpenAPI spec version: 20241201
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Supported service attachment for the listing revision.
 */
export interface CreateSupportedServiceAttachment
  extends model.CreateListingRevisionAttachmentDetails {
  /**
   * Name of the service
   */
  "serviceName": string;
  /**
   * Optional url to service information
   */
  "url"?: string;
  /**
   * Type of the service
   */
  "type": string;

  "attachmentType": string;
}

export namespace CreateSupportedServiceAttachment {
  export function getJsonObj(
    obj: CreateSupportedServiceAttachment,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.CreateListingRevisionAttachmentDetails.getJsonObj(
            obj
          ) as CreateSupportedServiceAttachment)),
      ...{}
    };

    return jsonObj;
  }
  export const attachmentType = "SUPPORTED_SERVICES";
  export function getDeserializedJsonObj(
    obj: CreateSupportedServiceAttachment,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.CreateListingRevisionAttachmentDetails.getDeserializedJsonObj(
            obj
          ) as CreateSupportedServiceAttachment)),
      ...{}
    };

    return jsonObj;
  }
}
