/**
 * MarketplacePublisherService API
 * Use the Marketplace Publisher API to manage the publishing of applications in Oracle Cloud Infrastructure Marketplace.
 * OpenAPI spec version: 20241201
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Details to update Machine Image Artifact.
 *
 */
export interface UpdateMachineImageArtifactDetails extends model.UpdateArtifactDetails {
  "machineImage"?: model.UpdateMachineImageDetails;

  "artifactType": string;
}

export namespace UpdateMachineImageArtifactDetails {
  export function getJsonObj(
    obj: UpdateMachineImageArtifactDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.UpdateArtifactDetails.getJsonObj(obj) as UpdateMachineImageArtifactDetails)),
      ...{
        "machineImage": obj.machineImage
          ? model.UpdateMachineImageDetails.getJsonObj(obj.machineImage)
          : undefined
      }
    };

    return jsonObj;
  }
  export const artifactType = "MACHINE_IMAGE";
  export function getDeserializedJsonObj(
    obj: UpdateMachineImageArtifactDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.UpdateArtifactDetails.getDeserializedJsonObj(
            obj
          ) as UpdateMachineImageArtifactDetails)),
      ...{
        "machineImage": obj.machineImage
          ? model.UpdateMachineImageDetails.getDeserializedJsonObj(obj.machineImage)
          : undefined
      }
    };

    return jsonObj;
  }
}
