/**
 * OCI Control Center Demand Signal API
 * Use the OCI Control Center Demand Signal API to manage Demand Signals.
 * OpenAPI spec version: 20240430
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Configuration for COMPUTE
 */
export interface ComputeResourceConfiguration extends model.BaseResourceConfiguration {
  /**
   * The shape of the compute instance.
   */
  "shape": string;
  /**
   * The hardware generation of the compute resource.
   */
  "computeHwGeneration"?: string;
  /**
   * The type of usage for the resource.
   */
  "usageType": string;

  "resource": string;
}

export namespace ComputeResourceConfiguration {
  export function getJsonObj(obj: ComputeResourceConfiguration, isParentJsonObj?: boolean): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.BaseResourceConfiguration.getJsonObj(obj) as ComputeResourceConfiguration)),
      ...{}
    };

    return jsonObj;
  }
  export const resource = "COMPUTE";
  export function getDeserializedJsonObj(
    obj: ComputeResourceConfiguration,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.BaseResourceConfiguration.getDeserializedJsonObj(
            obj
          ) as ComputeResourceConfiguration)),
      ...{}
    };

    return jsonObj;
  }
}
