/**
 * Oracle Database Autonomous Recovery Service API
 * Use Oracle Database Autonomous Recovery Service API to manage Protected Databases.
 * OpenAPI spec version: 20210216
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2023, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Possible database sizes.
 **/
export enum DatabaseSizes {
  Xs = "XS",
  S = "S",
  M = "M",
  L = "L",
  Xl = "XL",
  Xxl = "XXL",
  Auto = "AUTO",

  /**
   * This value is used if a service returns a value for this enum that is not recognized by this
   * version of the SDK.
   */
  UnknownValue = "UNKNOWN_VALUE"
}

export namespace DatabaseSizes {
  export function getJsonObj(obj: DatabaseSizes): DatabaseSizes {
    return obj;
  }
  export function getDeserializedJsonObj(obj: DatabaseSizes): DatabaseSizes {
    return obj;
  }
}
