/**
 * DevOps API
 * Use the DevOps API to create DevOps projects, configure code repositories,  add artifacts to deploy, build and test software applications, configure  target deployment environments, and deploy software applications.  For more information, see [DevOps](/Content/devops/using/home.htm).
 * OpenAPI spec version: 20210630
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * determines if this is a merge or a validation.
 */
export interface MergePullRequestDetails {
  "actionType": string;
}

export namespace MergePullRequestDetails {
  export function getJsonObj(obj: MergePullRequestDetails): object {
    const jsonObj = { ...obj, ...{} };

    if (obj && "actionType" in obj && obj.actionType) {
      switch (obj.actionType) {
        case "EXECUTE":
          return model.ExecuteMergePullRequestDetails.getJsonObj(
            <model.ExecuteMergePullRequestDetails>(<object>jsonObj),
            true
          );
        case "VALIDATE":
          return model.ValidateMergePullRequestDetails.getJsonObj(
            <model.ValidateMergePullRequestDetails>(<object>jsonObj),
            true
          );
        default:
          if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.actionType}`);
      }
    }
    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: MergePullRequestDetails): object {
    const jsonObj = { ...obj, ...{} };

    if (obj && "actionType" in obj && obj.actionType) {
      switch (obj.actionType) {
        case "EXECUTE":
          return model.ExecuteMergePullRequestDetails.getDeserializedJsonObj(
            <model.ExecuteMergePullRequestDetails>(<object>jsonObj),
            true
          );
        case "VALIDATE":
          return model.ValidateMergePullRequestDetails.getDeserializedJsonObj(
            <model.ValidateMergePullRequestDetails>(<object>jsonObj),
            true
          );
        default:
          if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.actionType}`);
      }
    }
    return jsonObj;
  }
}
