/**
 * DevOps API
 * Use the DevOps API to create DevOps projects, configure code repositories,  add artifacts to deploy, build and test software applications, configure  target deployment environments, and deploy software applications.  For more information, see [DevOps](/Content/devops/using/home.htm).
 * OpenAPI spec version: 20210630
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Specifies Trigger Deployment Pipleline stage specific run details.
 */
export interface TriggerDeploymentPipelineStageRunProgress
  extends model.BuildPipelineStageRunProgress {
  "exportedVariables"?: model.ExportedVariableCollection;
  "artifactOverrideParameters"?: model.DeployArtifactOverrideArgumentCollection;
  /**
   * Identifier of the deployment triggered.
   */
  "deploymentId"?: string;

  "buildPipelineStageType": string;
}

export namespace TriggerDeploymentPipelineStageRunProgress {
  export function getJsonObj(
    obj: TriggerDeploymentPipelineStageRunProgress,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.BuildPipelineStageRunProgress.getJsonObj(
            obj
          ) as TriggerDeploymentPipelineStageRunProgress)),
      ...{
        "exportedVariables": obj.exportedVariables
          ? model.ExportedVariableCollection.getJsonObj(obj.exportedVariables)
          : undefined,
        "artifactOverrideParameters": obj.artifactOverrideParameters
          ? model.DeployArtifactOverrideArgumentCollection.getJsonObj(
              obj.artifactOverrideParameters
            )
          : undefined
      }
    };

    return jsonObj;
  }
  export const buildPipelineStageType = "TRIGGER_DEPLOYMENT_PIPELINE";
  export function getDeserializedJsonObj(
    obj: TriggerDeploymentPipelineStageRunProgress,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.BuildPipelineStageRunProgress.getDeserializedJsonObj(
            obj
          ) as TriggerDeploymentPipelineStageRunProgress)),
      ...{
        "exportedVariables": obj.exportedVariables
          ? model.ExportedVariableCollection.getDeserializedJsonObj(obj.exportedVariables)
          : undefined,
        "artifactOverrideParameters": obj.artifactOverrideParameters
          ? model.DeployArtifactOverrideArgumentCollection.getDeserializedJsonObj(
              obj.artifactOverrideParameters
            )
          : undefined
      }
    };

    return jsonObj;
  }
}
