/**
 * Data Safe API
 * APIs for using Oracle Data Safe.
 * OpenAPI spec version: 20181201
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Summary of a subsetting schema present in subsetting policy.
 */
export interface SubsettingSchemaSummary {
  /**
   * The database schema present in subsetting policy which is to be subsetted.
   */
  "schemaName": string;
  /**
   * Indicates if the schema is a derived schema and not directly came as input from the user. A schema is derived if it is related to a input schema
   */
  "isDerived": boolean;
}

export namespace SubsettingSchemaSummary {
  export function getJsonObj(obj: SubsettingSchemaSummary): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: SubsettingSchemaSummary): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
}
