/**
 * MySQL Database Service API
 * The API for the MySQL Database Service
 * OpenAPI spec version: 20190415
 * Contact: mysql-cloud-dev_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * The source DB System identifier (OCID) and region from which the new DB system will be
 * cloned by copying its data. Optionally, channel properties can be provided to create a replication
 * channel between the newly created DB system and the source DB system.
 *
 */
export interface CreateDbSystemSourceFromDbSystemDetails extends model.CreateDbSystemSourceDetails {
  /**
   * The OCID of the DB system to be used as the source for the new DB System.
   *
   */
  "dbSystemId": string;
  /**
   * The region identifier of the source region where the DB system exists, only if it is in a different region.
   * If the source DB system is in the same region, then no region must be specified.
   * For more information, please see [Regions and Availability Domains](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm).
   *
   */
  "region"?: string;
  "channel"?: model.CreateDbSystemSourceFromDbSystemChannelDetails;

  "sourceType": string;
}

export namespace CreateDbSystemSourceFromDbSystemDetails {
  export function getJsonObj(
    obj: CreateDbSystemSourceFromDbSystemDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.CreateDbSystemSourceDetails.getJsonObj(
            obj
          ) as CreateDbSystemSourceFromDbSystemDetails)),
      ...{
        "channel": obj.channel
          ? model.CreateDbSystemSourceFromDbSystemChannelDetails.getJsonObj(obj.channel)
          : undefined
      }
    };

    return jsonObj;
  }
  export const sourceType = "DBSYSTEM";
  export function getDeserializedJsonObj(
    obj: CreateDbSystemSourceFromDbSystemDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.CreateDbSystemSourceDetails.getDeserializedJsonObj(
            obj
          ) as CreateDbSystemSourceFromDbSystemDetails)),
      ...{
        "channel": obj.channel
          ? model.CreateDbSystemSourceFromDbSystemChannelDetails.getDeserializedJsonObj(obj.channel)
          : undefined
      }
    };

    return jsonObj;
  }
}
