/**
 * MySQL Database Service API
 * The API for the MySQL Database Service
 * OpenAPI spec version: 20190415
 * Contact: mysql-cloud-dev_ww_grp@oracle.com
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * The Maintenance Policy for the DB System or Read Replica that this model is included in.
 *
 */
export interface MaintenanceDetails {
  /**
    * The start time of the maintenance window.
* <p>
This string is of the format: \"{day-of-week} {time-of-day}\".
* <p>
\"{day-of-week}\" is a case-insensitive string like \"mon\", \"tue\", &c.
* <p>
\"{time-of-day}\" is the \"Time\" portion of an RFC3339-formatted timestamp. Any second or sub-second time data will be truncated to zero.
* <p>
If you set the read replica maintenance window to \"\" or if not specified, the read replica is set same as the DB system maintenance window.
* 
    */
  "windowStartTime"?: string;
  /**
    * The preferred version to target when performing an automatic MySQL upgrade.
* <p>
OLDEST: Choose the oldest available MySQL version based on the current version of the DB System.
* SECOND_NEWEST: Choose the MySQL version before the newest for auto-upgrade.
* NEWEST: Choose the latest and greatest MySQL version available for auto-upgrade.
* 
    */
  "versionPreference"?: model.VersionPreference;
  /**
   * The preferred version track to target when performing an automatic MySQL upgrade.
   * LONG_TERM_SUPPORT: No MySQL database behavior changes.
   * INNOVATION:        Provides access to the latest features and all bug fixes.
   * FOLLOW:            Follows the track of the current MySQL version.
   *
   */
  "versionTrackPreference"?: model.VersionTrackPreference;
  /**
   * The maintenance schedule type of the DB system.
   * EARLY:   Maintenance schedule follows a cycle where upgrades are performed when versions become deprecated.
   * REGULAR: Maintenance schedule follows the normal cycle where upgrades are performed when versions become unavailable.
   *
   */
  "maintenanceScheduleType"?: model.MaintenanceScheduleType;
  /**
   * The time the scheduled maintenance is expected to start,
   * as described by [RFC 3339](https://tools.ietf.org/rfc/rfc3339).
   *
   */
  "timeScheduled"?: Date;
  /**
   * The version that is expected to be targeted during the next scheduled maintenance run.
   *
   */
  "targetVersion"?: string;
  /**
   * Time window during which downtime-inducing maintenance shall not be performed.
   * Downtime-free maintenance may be performed to apply required security patches.
   * At most one configured window is supported.
   *
   */
  "maintenanceDisabledWindows"?: Array<model.MaintenanceDisabledWindow>;
}

export namespace MaintenanceDetails {
  export function getJsonObj(obj: MaintenanceDetails): object {
    const jsonObj = {
      ...obj,
      ...{
        "maintenanceDisabledWindows": obj.maintenanceDisabledWindows
          ? obj.maintenanceDisabledWindows.map(item => {
              return model.MaintenanceDisabledWindow.getJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: MaintenanceDetails): object {
    const jsonObj = {
      ...obj,
      ...{
        "maintenanceDisabledWindows": obj.maintenanceDisabledWindows
          ? obj.maintenanceDisabledWindows.map(item => {
              return model.MaintenanceDisabledWindow.getDeserializedJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
}
