/**
 * OpenSearch Service API
 * The OpenSearch service API provides access to OCI Search Service with OpenSearch.
 * OpenAPI spec version: 20180828
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as BackupOpensearchClusterResponse from "./backup-opensearch-cluster-response";
export import BackupOpensearchClusterResponse = BackupOpensearchClusterResponse.BackupOpensearchClusterResponse;
import * as CreateOpensearchClusterResponse from "./create-opensearch-cluster-response";
export import CreateOpensearchClusterResponse = CreateOpensearchClusterResponse.CreateOpensearchClusterResponse;
import * as DeleteOpensearchClusterResponse from "./delete-opensearch-cluster-response";
export import DeleteOpensearchClusterResponse = DeleteOpensearchClusterResponse.DeleteOpensearchClusterResponse;
import * as GetOpensearchClusterResponse from "./get-opensearch-cluster-response";
export import GetOpensearchClusterResponse = GetOpensearchClusterResponse.GetOpensearchClusterResponse;
import * as GetWorkRequestResponse from "./get-work-request-response";
export import GetWorkRequestResponse = GetWorkRequestResponse.GetWorkRequestResponse;
import * as ListOpensearchClustersResponse from "./list-opensearch-clusters-response";
export import ListOpensearchClustersResponse = ListOpensearchClustersResponse.ListOpensearchClustersResponse;
import * as ListOpensearchVersionsResponse from "./list-opensearch-versions-response";
export import ListOpensearchVersionsResponse = ListOpensearchVersionsResponse.ListOpensearchVersionsResponse;
import * as ListWorkRequestErrorsResponse from "./list-work-request-errors-response";
export import ListWorkRequestErrorsResponse = ListWorkRequestErrorsResponse.ListWorkRequestErrorsResponse;
import * as ListWorkRequestLogsResponse from "./list-work-request-logs-response";
export import ListWorkRequestLogsResponse = ListWorkRequestLogsResponse.ListWorkRequestLogsResponse;
import * as ListWorkRequestsResponse from "./list-work-requests-response";
export import ListWorkRequestsResponse = ListWorkRequestsResponse.ListWorkRequestsResponse;
import * as OpensearchClusterRestoreResponse from "./opensearch-cluster-restore-response";
export import OpensearchClusterRestoreResponse = OpensearchClusterRestoreResponse.OpensearchClusterRestoreResponse;
import * as ResizeOpensearchClusterHorizontalResponse from "./resize-opensearch-cluster-horizontal-response";
export import ResizeOpensearchClusterHorizontalResponse = ResizeOpensearchClusterHorizontalResponse.ResizeOpensearchClusterHorizontalResponse;
import * as ResizeOpensearchClusterVerticalResponse from "./resize-opensearch-cluster-vertical-response";
export import ResizeOpensearchClusterVerticalResponse = ResizeOpensearchClusterVerticalResponse.ResizeOpensearchClusterVerticalResponse;
import * as UpdateOpensearchClusterResponse from "./update-opensearch-cluster-response";
export import UpdateOpensearchClusterResponse = UpdateOpensearchClusterResponse.UpdateOpensearchClusterResponse;
import * as DeleteOpensearchClusterBackupResponse from "./delete-opensearch-cluster-backup-response";
export import DeleteOpensearchClusterBackupResponse = DeleteOpensearchClusterBackupResponse.DeleteOpensearchClusterBackupResponse;
import * as GetOpensearchClusterBackupResponse from "./get-opensearch-cluster-backup-response";
export import GetOpensearchClusterBackupResponse = GetOpensearchClusterBackupResponse.GetOpensearchClusterBackupResponse;
import * as ListOpensearchClusterBackupsResponse from "./list-opensearch-cluster-backups-response";
export import ListOpensearchClusterBackupsResponse = ListOpensearchClusterBackupsResponse.ListOpensearchClusterBackupsResponse;
import * as UpdateOpensearchClusterBackupResponse from "./update-opensearch-cluster-backup-response";
export import UpdateOpensearchClusterBackupResponse = UpdateOpensearchClusterBackupResponse.UpdateOpensearchClusterBackupResponse;
