/**
 * Globally Distributed Database
 * Use the Globally Distributed Database service APIs to create and manage the Globally distributed databases.
 * OpenAPI spec version: 20250101
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Details required for creation of autonomous dedicated infrastructure based shard peer.
 */
export interface CreateShardPeerWithDedicatedInfraDetails {
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the cloud Autonomous VM Cluster for the peer shard.
   */
  "cloudAutonomousVmClusterId": string;
  /**
   * The protectionMode for the shard peer.
   */
  "protectionMode"?: model.DistributedAutonomousDbProtectionMode;
  /**
   * The lag time preference based on data loss tolerance in seconds. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "fastStartFailOverLagLimitInSeconds"?: number;
  /**
   * Indicates whether Automatic Failover is enabled for Autonomous Container Database Dataguard Association
   *
   */
  "isAutomaticFailoverEnabled"?: boolean;
  /**
   * The scheduling detail for the quarterly maintenance window of the standby Autonomous Container Database.
   * This value represents the number of days before schedlued maintenance of the primary database.
   *  Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "standbyMaintenanceBufferInDays"?: number;
}

export namespace CreateShardPeerWithDedicatedInfraDetails {
  export function getJsonObj(obj: CreateShardPeerWithDedicatedInfraDetails): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: CreateShardPeerWithDedicatedInfraDetails): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
}
