/**
 * Connector Hub API
 * Use the Connector Hub API to transfer data between services in Oracle Cloud Infrastructure.
For more information about Connector Hub, see
[the Connector Hub documentation](https://docs.oracle.com/iaas/Content/connector-hub/home.htm).
Connector Hub is formerly known as Service Connector Hub.

 * OpenAPI spec version: 20200909
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as requests from "./lib/request";
import * as models from "./lib/model";
import * as responses from "./lib/response";
import * as client from "./lib/client";
import * as connectorplugins_waiter from "./lib/connectorplugins-waiter";
import * as serviceconnector_waiter from "./lib/serviceconnector-waiter";

export { models };
export { requests };
export { responses };
export import ConnectorPluginsClient = client.ConnectorPluginsClient;
export import ConnectorPluginsWaiter = connectorplugins_waiter.ConnectorPluginsWaiter;
export import ServiceConnectorClient = client.ServiceConnectorClient;
export import ServiceConnectorWaiter = serviceconnector_waiter.ServiceConnectorWaiter;
