/**
 * Analytics API
 * Analytics API.

 * OpenAPI spec version: 20190331
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Private endpoint configuration details.
 *
 */
export interface PrivateEndpointDetails extends model.NetworkEndpointDetails {
  /**
   * The VCN OCID for the private endpoint.
   *
   */
  "vcnId": string;
  /**
   * The subnet OCID for the private endpoint.
   *
   */
  "subnetId": string;
  /**
   * Network Security Group OCIDs for an Analytics instance.
   *
   */
  "networkSecurityGroupIds"?: Array<string>;

  "networkEndpointType": string;
}

export namespace PrivateEndpointDetails {
  export function getJsonObj(obj: PrivateEndpointDetails, isParentJsonObj?: boolean): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.NetworkEndpointDetails.getJsonObj(obj) as PrivateEndpointDetails)),
      ...{}
    };

    return jsonObj;
  }
  export const networkEndpointType = "PRIVATE";
  export function getDeserializedJsonObj(
    obj: PrivateEndpointDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.NetworkEndpointDetails.getDeserializedJsonObj(obj) as PrivateEndpointDetails)),
      ...{}
    };

    return jsonObj;
  }
}
