/**
 * Web Application Firewall (WAF) API
 * API for the Web Application Firewall service.
Use this API to manage regional Web App Firewalls and corresponding policies for protecting HTTP services.

 * OpenAPI spec version: 20210930
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Rule that represents Request/Response Access Control.
 * Only actions of the following types are allowed to be referenced in this rule:
 *  * CHECK
 *  * ALLOW
 *  * RETURN_HTTP_RESPONSE
 *
 */
export interface AccessControlRule extends model.WebAppFirewallPolicyRule {
  "type": string;
}

export namespace AccessControlRule {
  export function getJsonObj(obj: AccessControlRule, isParentJsonObj?: boolean): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.WebAppFirewallPolicyRule.getJsonObj(obj) as AccessControlRule)),
      ...{}
    };

    return jsonObj;
  }
  export const type = "ACCESS_CONTROL";
  export function getDeserializedJsonObj(
    obj: AccessControlRule,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.WebAppFirewallPolicyRule.getDeserializedJsonObj(obj) as AccessControlRule)),
      ...{}
    };

    return jsonObj;
  }
}
