/**
 * Certificates Service Management API
 * API for managing certificates.
 * OpenAPI spec version: 20210224
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * A constraint that specifies permitted and excluded namespaces for the hierarchical name forms in certificates that any CA in the certificate chain issues. You can define name constraints on a directory name, DNS address, or IP address. If you have a name constraint, you must define at least one permitted namespace or one excluded namespace.
 *
 */
export interface NameConstraint {
  /**
   * A list that contains permitted namespaces. If you have a name constraint with no excluded namespaces, you must specify at least one permitted namespace.
   *
   */
  "permittedSubtree"?: Array<model.NameConstraintSubtreeNode>;
  /**
   * A list that contains excluded (or prohibited) namespaces. If you have a name constraint with no permitted namespaces, you must specify at least one excluded namespace.
   *
   */
  "excludedSubtree"?: Array<model.NameConstraintSubtreeNode>;
}

export namespace NameConstraint {
  export function getJsonObj(obj: NameConstraint): object {
    const jsonObj = {
      ...obj,
      ...{
        "permittedSubtree": obj.permittedSubtree
          ? obj.permittedSubtree.map(item => {
              return model.NameConstraintSubtreeNode.getJsonObj(item);
            })
          : undefined,
        "excludedSubtree": obj.excludedSubtree
          ? obj.excludedSubtree.map(item => {
              return model.NameConstraintSubtreeNode.getJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: NameConstraint): object {
    const jsonObj = {
      ...obj,
      ...{
        "permittedSubtree": obj.permittedSubtree
          ? obj.permittedSubtree.map(item => {
              return model.NameConstraintSubtreeNode.getDeserializedJsonObj(item);
            })
          : undefined,
        "excludedSubtree": obj.excludedSubtree
          ? obj.excludedSubtree.map(item => {
              return model.NameConstraintSubtreeNode.getDeserializedJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
}
