/**
 * Oracle Cloud Migrations API
 * A description of the Oracle Cloud Migrations API.
 * OpenAPI spec version: 20220919
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Replication location detail where the snapshots reside
 */
export interface ReplicationLocationDetail {
  /**
   * The type of replication location
   */
  "replicationLocationType"?: ReplicationLocationDetail.ReplicationLocationType;
  /**
   * Properties for each of the replication location types
   */
  "metadata"?: any;
}

export namespace ReplicationLocationDetail {
  export enum ReplicationLocationType {
    OciObjectStore = "OCI_OBJECT_STORE",
    OlvmStorageDomain = "OLVM_STORAGE_DOMAIN",
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
  }

  export function getJsonObj(obj: ReplicationLocationDetail): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: ReplicationLocationDetail): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
}
