/**
 * Queue API
 * Use the Queue API to produce and consume messages, create queues, and manage related items. For more information, see [Queue](https://docs.oracle.com/iaas/Content/queue/overview.htm).
 * OpenAPI spec version: 20210201
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Base object for capabilities
 */
export interface CapabilityDetails {
  "type": string;
}

export namespace CapabilityDetails {
  export function getJsonObj(obj: CapabilityDetails): object {
    const jsonObj = { ...obj, ...{} };

    if (obj && "type" in obj && obj.type) {
      switch (obj.type) {
        case "LARGE_MESSAGES":
          return model.LargeMessagesCapabilityDetails.getJsonObj(
            <model.LargeMessagesCapabilityDetails>(<object>jsonObj),
            true
          );
        case "CONSUMER_GROUPS":
          return model.ConsumerGroupsCapabilityDetails.getJsonObj(
            <model.ConsumerGroupsCapabilityDetails>(<object>jsonObj),
            true
          );
        default:
          if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.type}`);
      }
    }
    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: CapabilityDetails): object {
    const jsonObj = { ...obj, ...{} };

    if (obj && "type" in obj && obj.type) {
      switch (obj.type) {
        case "LARGE_MESSAGES":
          return model.LargeMessagesCapabilityDetails.getDeserializedJsonObj(
            <model.LargeMessagesCapabilityDetails>(<object>jsonObj),
            true
          );
        case "CONSUMER_GROUPS":
          return model.ConsumerGroupsCapabilityDetails.getDeserializedJsonObj(
            <model.ConsumerGroupsCapabilityDetails>(<object>jsonObj),
            true
          );
        default:
          if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.type}`);
      }
    }
    return jsonObj;
  }
}
