/**
 *
 *
 * OpenAPI spec version: 20250531
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * @example Click {@link https://docs.oracle.com/en-us/iaas/tools/typescript-sdk-examples/latest/iot/ListDigitalTwinRelationships.ts.html |here} to see how to use ListDigitalTwinRelationshipsRequest.
 */
export interface ListDigitalTwinRelationshipsRequest extends common.BaseRequest {
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the IoT domain in which to list digital twin resources.
   *
   */
  "iotDomainId": string;
  /**
   * Filter resources whose display name matches the specified value.
   *
   */
  "displayName"?: string;
  /**
   * Filters resources that match the content path of the digital twin relationship.
   *
   */
  "contentPath"?: string;
  /**
   * Filter resources that match the specified [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of source digital twin instance.
   *
   */
  "sourceDigitalTwinInstanceId"?: string;
  /**
   * Filter resources that match the specified [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of target digital twin instance.
   *
   */
  "targetDigitalTwinInstanceId"?: string;
  /**
   * Filter resources whose lifecycleState matches the specified value.
   *
   */
  "lifecycleState"?: model.LifecycleState;
  /**
   * For list pagination. The maximum number of results per page, or items to return in a
   * paginated \"List\" call. For important details about how pagination works, see
   * [List Pagination](https://docs.oracle.com/iaas/Content/API/Concepts/usingapi.htm#nine).
   *
   */
  "limit"?: number;
  /**
   * Page representing the requested page of items.
   */
  "page"?: string;
  /**
   * Specifies sort order to use, either ASC (ascending) or DESC (descending).
   */
  "sortOrder"?: ListDigitalTwinRelationshipsRequest.SortOrder;
  /**
   * The field to sort by. Only one sort order may be provided.
   * Default order for timeCreated is descending. Default order for displayName is ascending.
   *
   */
  "sortBy"?: ListDigitalTwinRelationshipsRequest.SortBy;
  /**
   * Unique Oracle-assigned identifier for the request.
   * If you need to contact Oracle about a particular request, provide the request ID.
   *
   */
  "opcRequestId"?: string;
  /**
   * Filter resources by [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm). Must be a valid OCID of the resource type.
   *
   */
  "id"?: string;
}

export namespace ListDigitalTwinRelationshipsRequest {
  export enum SortOrder {
    Asc = "ASC",
    Desc = "DESC"
  }

  export enum SortBy {
    TimeCreated = "timeCreated",
    DisplayName = "displayName"
  }
}
