/**
 * API Gateway API
 * API for the API Gateway service. Use this API to manage gateways, deployments, and related items.
For more information, see
[Overview of API Gateway](/iaas/Content/APIGateway/Concepts/apigatewayoverview.htm).

 * OpenAPI spec version: 20190501
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Information about the new gateway.
 */
export interface CreateGatewayDetails {
  /**
    * A user-friendly name. Does not have to be unique, and it's changeable.
* Avoid entering confidential information.
* <p>
Example: `My new resource`
* 
    */
  "displayName"?: string;
  /**
   * The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the compartment in which the
   * resource is created.
   *
   */
  "compartmentId": string;
  /**
    * Gateway endpoint type. `PUBLIC` will have a public ip address assigned to it, while `PRIVATE` will only be
* accessible on a private IP address on the subnet.
* <p>
Example: `PUBLIC` or `PRIVATE`
* 
    */
  "endpointType": string;
  /**
   * The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the subnet in which
   * related resources are created.
   *
   */
  "subnetId": string;
  /**
   * An array of Network Security Groups OCIDs associated with this API Gateway.
   *
   */
  "networkSecurityGroupIds"?: Array<string>;
  /**
   * The [OCID](https://docs.cloud.oracle.com/Content/General/Concepts/identifiers.htm) of the resource.
   *
   */
  "certificateId"?: string;
  "responseCacheDetails"?: model.ExternalRespCache | model.NoCache;
  /**
    * Free-form tags for this resource. Each tag is a simple key-value pair
* with no predefined name, type, or namespace. For more information, see
* [Resource Tags](https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
* <p>
Example: `{\"Department\": \"Finance\"}`
* 
    */
  "freeformTags"?: { [key: string]: string };
  /**
    * Defined tags for this resource. Each key is predefined and scoped to a
* namespace. For more information, see
* [Resource Tags](https://docs.cloud.oracle.com/Content/General/Concepts/resourcetags.htm).
* <p>
Example: `{\"Operations\": {\"CostCenter\": \"42\"}}`
* 
    */
  "definedTags"?: { [key: string]: { [key: string]: any } };
  /**
   * An array of CA bundles that should be used on the Gateway for TLS validation.
   */
  "caBundles"?: Array<model.CaBundle>;
}

export namespace CreateGatewayDetails {
  export function getJsonObj(obj: CreateGatewayDetails): object {
    const jsonObj = {
      ...obj,
      ...{
        "responseCacheDetails": obj.responseCacheDetails
          ? model.ResponseCacheDetails.getJsonObj(obj.responseCacheDetails)
          : undefined,

        "caBundles": obj.caBundles
          ? obj.caBundles.map(item => {
              return model.CaBundle.getJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: CreateGatewayDetails): object {
    const jsonObj = {
      ...obj,
      ...{
        "responseCacheDetails": obj.responseCacheDetails
          ? model.ResponseCacheDetails.getDeserializedJsonObj(obj.responseCacheDetails)
          : undefined,

        "caBundles": obj.caBundles
          ? obj.caBundles.map(item => {
              return model.CaBundle.getDeserializedJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
}
