/**
 * Globally Distributed Database
 * Use the Globally Distributed Database service APIs to create and manage the Globally distributed databases.
 * OpenAPI spec version: 20260101
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Globally distributed autonomous database.
 */
export interface DistributedAutonomousDatabase {
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Globally distributed autonomous database.
   */
  "id": string;
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Globally distributed autonomous database compartment.
   */
  "compartmentId": string;
  /**
   * The display name of the Globally distributed autonomous database.
   */
  "displayName": string;
  /**
   * The time the Globally distributed autonomous database was created. An RFC3339 formatted datetime string.
   */
  "timeCreated": Date;
  /**
   * The time the Globally distributed autonomous database was last updated. An RFC3339 formatted datetime string.
   */
  "timeUpdated": Date;
  /**
   * Oracle Database version for the shards and catalog used in Globally distributed autonomous database.
   */
  "databaseVersion": string;
  /**
   * Lifecycle states for the Globally distributed autonomous database.
   */
  "lifecycleState": DistributedAutonomousDatabase.LifecycleState;
  /**
   * Sharding methods for the Globally distributed autonomous database.
   */
  "shardingMethod": DistributedAutonomousDatabase.ShardingMethod;
  /**
   * The Replication method for Globally distributed Autonomous database. Use RAFT for Raft based replication.
   * With RAFT replication, shards cannot have peers details set on them. In case shards need to
   * have peers, please do not set RAFT replicationMethod. For all non RAFT replication cases (with or
   * without peers), please set replicationMethod as DG or do not set any value for replicationMethod.
   *
   */
  "replicationMethod"?: DistributedAutonomousDatabase.ReplicationMethod;
  /**
   * The distributed autonomous database deployment type.
   *
   */
  "dbDeploymentType": DistributedAutonomousDatabase.DbDeploymentType;
  /**
   * The lifecycleDetails for the Globally distributed autonomous database.
   */
  "lifecycleDetails": string;
  "connectionStrings"?: model.DistributedAutonomousDatabaseConnectionString;
  /**
   * Unique name prefix for the Globally distributed autonomous databases. Only alpha-numeric values are allowed. First character
   * has to be a letter followed by any combination of letter and number.
   *
   */
  "prefix": string;
  /**
   * The collection of [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the private endpoint associated with Globally distributed autonomous database.
   */
  "privateEndpointIds": Array<string>;
  /**
   * The collection of [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) for the notification topics associated with the globally distributed autonomous database.
   */
  "notificationTopicIds"?: Array<string>;
  /**
   * Possible workload types. Currently only OLTP workload type is supported.
   */
  "dbWorkloadType": DistributedAutonomousDatabase.DbWorkloadType;
  /**
   * The character set for the database.
   */
  "characterSet": string;
  /**
   * The national character set for the database.
   */
  "ncharacterSet": string;
  /**
   * The listener port number for the Globally distributed autonomous database. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "listenerPort": number;
  /**
   * The TLS listener port number for Globally distributed autonomous database. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "listenerPortTls"?: number;
  /**
   * Ons local port number for Globally distributed autonomous database. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "onsPortLocal": number;
  /**
   * Ons remote port number for Globally distributed autonomous database. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "onsPortRemote": number;
  /**
   * Count of chunks associated with system raft clusters or system data guard databases. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "systemChunkCount"?: number;
  /**
   * Number of replication units associated with system raft clusters. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "systemRaftReplicationUnitCount"?: number;
  "latestGsmImage"?: model.DistributedAutonomousDatabaseGsmImage;
  /**
   * Collection of composite raft shards.
   */
  "compositeRaftShardSpaces"?: Array<model.AutonomousCompositeRaftShardSpace>;
  /**
   * Collection of composite data guard shard spaces.
   */
  "compositeDataGuardShardSpaces"?: Array<model.AutonomousCompositeDataGuardShardSpace>;
  /**
   * Collection of system raft clusters.
   */
  "systemRaftClusters"?: Array<model.AutonomousSystemRaftCluster>;
  "systemDataGuardDatabases"?: model.AutonomousSystemDataGuardDatabase;
  /**
   * Collection of user defined shard spaces.
   */
  "userShardSpaces"?: Array<model.AutonomousUserShardSpace>;
  /**
   * Catalog details associated with the distributed autonomous database.
   */
  "catalogDetails"?: Array<model.DistributedAutonomousDatabaseCatalog>;
  /**
   * Global Service Manager (GSM) instances associated with the distributed autonomous database.
   */
  "gsmDetails"?: Array<model.DistributedAutonomousDatabaseGsm>;
  /**
   * Global Database Services Control(GDS CTL) instances associated with the distributed autonomous database.
   */
  "gdsControlNodeDetails"?: Array<model.DistributedAutonomousDatabaseGdsControlNode>;
  "dbBackupConfig"?: model.DistributedAutonomousDbBackupConfig;
  "autoResourceManagementConfig"?: model.AutoResourceManagementConfigurationDetails;
  /**
   * The list of network security group (NSG) details associated with the distributed autonomous database.
   */
  "vcnNsgIds"?: Array<model.VcnNsgIdsDetails>;
  "metadata"?: model.DistributedAutonomousDbMetadata;
  /**
   * Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
   * Example: {@code {\"bar-key\": \"value\"}}
   *
   */
  "freeformTags"?: { [key: string]: string };
  /**
   * Defined tags for this resource. Each key is predefined and scoped to a namespace.
   * Example: {@code {\"foo-namespace\": {\"bar-key\": \"value\"}}}
   *
   */
  "definedTags"?: { [key: string]: { [key: string]: any } };
  /**
   * Usage of system tag keys. These predefined keys are scoped to namespaces.
   * Example: {@code {\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}}
   *
   */
  "systemTags"?: { [key: string]: { [key: string]: any } };
}

export namespace DistributedAutonomousDatabase {
  export enum LifecycleState {
    Active = "ACTIVE",
    Failed = "FAILED",
    NeedsAttention = "NEEDS_ATTENTION",
    Inactive = "INACTIVE",
    Deleting = "DELETING",
    Deleted = "DELETED",
    Updating = "UPDATING",
    Creating = "CREATING",
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
  }

  export enum ShardingMethod {
    User = "USER",
    System = "SYSTEM",
    Composite = "COMPOSITE",
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
  }

  export enum ReplicationMethod {
    Raft = "RAFT",
    Dg = "DG",
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
  }

  export enum DbDeploymentType {
    AdbD = "ADB_D",
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
  }

  export enum DbWorkloadType {
    Oltp = "OLTP",
    Dw = "DW",
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
  }

  export function getJsonObj(obj: DistributedAutonomousDatabase): object {
    const jsonObj = {
      ...obj,
      ...{
        "connectionStrings": obj.connectionStrings
          ? model.DistributedAutonomousDatabaseConnectionString.getJsonObj(obj.connectionStrings)
          : undefined,

        "latestGsmImage": obj.latestGsmImage
          ? model.DistributedAutonomousDatabaseGsmImage.getJsonObj(obj.latestGsmImage)
          : undefined,
        "compositeRaftShardSpaces": obj.compositeRaftShardSpaces
          ? obj.compositeRaftShardSpaces.map(item => {
              return model.AutonomousCompositeRaftShardSpace.getJsonObj(item);
            })
          : undefined,
        "compositeDataGuardShardSpaces": obj.compositeDataGuardShardSpaces
          ? obj.compositeDataGuardShardSpaces.map(item => {
              return model.AutonomousCompositeDataGuardShardSpace.getJsonObj(item);
            })
          : undefined,
        "systemRaftClusters": obj.systemRaftClusters
          ? obj.systemRaftClusters.map(item => {
              return model.AutonomousSystemRaftCluster.getJsonObj(item);
            })
          : undefined,
        "systemDataGuardDatabases": obj.systemDataGuardDatabases
          ? model.AutonomousSystemDataGuardDatabase.getJsonObj(obj.systemDataGuardDatabases)
          : undefined,
        "userShardSpaces": obj.userShardSpaces
          ? obj.userShardSpaces.map(item => {
              return model.AutonomousUserShardSpace.getJsonObj(item);
            })
          : undefined,
        "catalogDetails": obj.catalogDetails
          ? obj.catalogDetails.map(item => {
              return model.DistributedAutonomousDatabaseCatalog.getJsonObj(item);
            })
          : undefined,
        "gsmDetails": obj.gsmDetails
          ? obj.gsmDetails.map(item => {
              return model.DistributedAutonomousDatabaseGsm.getJsonObj(item);
            })
          : undefined,
        "gdsControlNodeDetails": obj.gdsControlNodeDetails
          ? obj.gdsControlNodeDetails.map(item => {
              return model.DistributedAutonomousDatabaseGdsControlNode.getJsonObj(item);
            })
          : undefined,
        "dbBackupConfig": obj.dbBackupConfig
          ? model.DistributedAutonomousDbBackupConfig.getJsonObj(obj.dbBackupConfig)
          : undefined,
        "autoResourceManagementConfig": obj.autoResourceManagementConfig
          ? model.AutoResourceManagementConfigurationDetails.getJsonObj(
              obj.autoResourceManagementConfig
            )
          : undefined,
        "vcnNsgIds": obj.vcnNsgIds
          ? obj.vcnNsgIds.map(item => {
              return model.VcnNsgIdsDetails.getJsonObj(item);
            })
          : undefined,
        "metadata": obj.metadata
          ? model.DistributedAutonomousDbMetadata.getJsonObj(obj.metadata)
          : undefined
      }
    };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: DistributedAutonomousDatabase): object {
    const jsonObj = {
      ...obj,
      ...{
        "connectionStrings": obj.connectionStrings
          ? model.DistributedAutonomousDatabaseConnectionString.getDeserializedJsonObj(
              obj.connectionStrings
            )
          : undefined,

        "latestGsmImage": obj.latestGsmImage
          ? model.DistributedAutonomousDatabaseGsmImage.getDeserializedJsonObj(obj.latestGsmImage)
          : undefined,
        "compositeRaftShardSpaces": obj.compositeRaftShardSpaces
          ? obj.compositeRaftShardSpaces.map(item => {
              return model.AutonomousCompositeRaftShardSpace.getDeserializedJsonObj(item);
            })
          : undefined,
        "compositeDataGuardShardSpaces": obj.compositeDataGuardShardSpaces
          ? obj.compositeDataGuardShardSpaces.map(item => {
              return model.AutonomousCompositeDataGuardShardSpace.getDeserializedJsonObj(item);
            })
          : undefined,
        "systemRaftClusters": obj.systemRaftClusters
          ? obj.systemRaftClusters.map(item => {
              return model.AutonomousSystemRaftCluster.getDeserializedJsonObj(item);
            })
          : undefined,
        "systemDataGuardDatabases": obj.systemDataGuardDatabases
          ? model.AutonomousSystemDataGuardDatabase.getDeserializedJsonObj(
              obj.systemDataGuardDatabases
            )
          : undefined,
        "userShardSpaces": obj.userShardSpaces
          ? obj.userShardSpaces.map(item => {
              return model.AutonomousUserShardSpace.getDeserializedJsonObj(item);
            })
          : undefined,
        "catalogDetails": obj.catalogDetails
          ? obj.catalogDetails.map(item => {
              return model.DistributedAutonomousDatabaseCatalog.getDeserializedJsonObj(item);
            })
          : undefined,
        "gsmDetails": obj.gsmDetails
          ? obj.gsmDetails.map(item => {
              return model.DistributedAutonomousDatabaseGsm.getDeserializedJsonObj(item);
            })
          : undefined,
        "gdsControlNodeDetails": obj.gdsControlNodeDetails
          ? obj.gdsControlNodeDetails.map(item => {
              return model.DistributedAutonomousDatabaseGdsControlNode.getDeserializedJsonObj(item);
            })
          : undefined,
        "dbBackupConfig": obj.dbBackupConfig
          ? model.DistributedAutonomousDbBackupConfig.getDeserializedJsonObj(obj.dbBackupConfig)
          : undefined,
        "autoResourceManagementConfig": obj.autoResourceManagementConfig
          ? model.AutoResourceManagementConfigurationDetails.getDeserializedJsonObj(
              obj.autoResourceManagementConfig
            )
          : undefined,
        "vcnNsgIds": obj.vcnNsgIds
          ? obj.vcnNsgIds.map(item => {
              return model.VcnNsgIdsDetails.getDeserializedJsonObj(item);
            })
          : undefined,
        "metadata": obj.metadata
          ? model.DistributedAutonomousDbMetadata.getDeserializedJsonObj(obj.metadata)
          : undefined
      }
    };

    return jsonObj;
  }
}
