/**
 * Data Science API
 * Use the Data Science API to organize your data science work, access data and computing resources, and build, train, deploy and manage models and model deployments. For more information, see [Data Science](https://docs.oracle.com/iaas/data-science/using/data-science.htm).

 * OpenAPI spec version: 20190101
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Parameters needed to cloning a model group from an existing model group.
 */
export interface CloneCreateFromModelGroupDetails extends model.ModelGroupCloneSourceDetails {
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the model group to be cloned.
   */
  "sourceId": string;
  "modifyModelGroupDetails"?: model.ModifyModelGroupDetails;
  "patchModelGroupMemberModelDetails"?: model.PatchModelGroupMemberModelDetails;

  "modelGroupCloneSourceType": string;
}

export namespace CloneCreateFromModelGroupDetails {
  export function getJsonObj(
    obj: CloneCreateFromModelGroupDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.ModelGroupCloneSourceDetails.getJsonObj(obj) as CloneCreateFromModelGroupDetails)),
      ...{
        "modifyModelGroupDetails": obj.modifyModelGroupDetails
          ? model.ModifyModelGroupDetails.getJsonObj(obj.modifyModelGroupDetails)
          : undefined,
        "patchModelGroupMemberModelDetails": obj.patchModelGroupMemberModelDetails
          ? model.PatchModelGroupMemberModelDetails.getJsonObj(
              obj.patchModelGroupMemberModelDetails
            )
          : undefined
      }
    };

    return jsonObj;
  }
  export const modelGroupCloneSourceType = "MODEL_GROUP";
  export function getDeserializedJsonObj(
    obj: CloneCreateFromModelGroupDetails,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.ModelGroupCloneSourceDetails.getDeserializedJsonObj(
            obj
          ) as CloneCreateFromModelGroupDetails)),
      ...{
        "modifyModelGroupDetails": obj.modifyModelGroupDetails
          ? model.ModifyModelGroupDetails.getDeserializedJsonObj(obj.modifyModelGroupDetails)
          : undefined,
        "patchModelGroupMemberModelDetails": obj.patchModelGroupMemberModelDetails
          ? model.PatchModelGroupMemberModelDetails.getDeserializedJsonObj(
              obj.patchModelGroupMemberModelDetails
            )
          : undefined
      }
    };

    return jsonObj;
  }
}
