/**
 * Data Science API
 * Use the Data Science API to organize your data science work, access data and computing resources, and build, train, deploy and manage models and model deployments. For more information, see [Data Science](https://docs.oracle.com/iaas/data-science/using/data-science.htm).

 * OpenAPI spec version: 20190101
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * AuthN/Z configuration for online prediction
 */
export interface CreateAuthConfigurationDetails {
  "type": string;
}

export namespace CreateAuthConfigurationDetails {
  export function getJsonObj(obj: CreateAuthConfigurationDetails): object {
    const jsonObj = { ...obj, ...{} };

    if (obj && "type" in obj && obj.type) {
      switch (obj.type) {
        case "IDCS":
          return model.CreateIdcsAuthConfigurationDetails.getJsonObj(
            <model.CreateIdcsAuthConfigurationDetails>(<object>jsonObj),
            true
          );
        case "IDCS_CUSTOM_SERVICE":
          return model.CreateIdcsCustomServiceAuthConfigurationDetails.getJsonObj(
            <model.CreateIdcsCustomServiceAuthConfigurationDetails>(<object>jsonObj),
            true
          );
        case "IAM":
          return model.CreateIamAuthConfigurationCreateDetails.getJsonObj(
            <model.CreateIamAuthConfigurationCreateDetails>(<object>jsonObj),
            true
          );
        default:
          if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.type}`);
      }
    }
    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: CreateAuthConfigurationDetails): object {
    const jsonObj = { ...obj, ...{} };

    if (obj && "type" in obj && obj.type) {
      switch (obj.type) {
        case "IDCS":
          return model.CreateIdcsAuthConfigurationDetails.getDeserializedJsonObj(
            <model.CreateIdcsAuthConfigurationDetails>(<object>jsonObj),
            true
          );
        case "IDCS_CUSTOM_SERVICE":
          return model.CreateIdcsCustomServiceAuthConfigurationDetails.getDeserializedJsonObj(
            <model.CreateIdcsCustomServiceAuthConfigurationDetails>(<object>jsonObj),
            true
          );
        case "IAM":
          return model.CreateIamAuthConfigurationCreateDetails.getDeserializedJsonObj(
            <model.CreateIamAuthConfigurationCreateDetails>(<object>jsonObj),
            true
          );
        default:
          if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.type}`);
      }
    }
    return jsonObj;
  }
}
