/**
 * Core Services API
 * Use the Core Services API to manage resources such as virtual cloud networks (VCNs),
compute instances, and block storage volumes. For more information, see the console
documentation for the [Networking](https://docs.oracle.com/iaas/Content/Network/Concepts/overview.htm),
[Compute](https://docs.oracle.com/iaas/Content/Compute/Concepts/computeoverview.htm), and
[Block Volume](https://docs.oracle.com/iaas/Content/Block/Concepts/overview.htm) services.
The required permissions are documented in the
[Details for the Core Services](https://docs.oracle.com/iaas/Content/Identity/Reference/corepolicyreference.htm) article.

 * OpenAPI spec version: 20160918
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Configuration settings for GPU Memory Cluster scaling.
 *
 */
export interface UpdateComputeGpuMemoryClusterScaleConfig {
  /**
   * Enables upsizing towards the target size.
   *
   */
  "isUpsizeEnabled"?: boolean;
  /**
   * Enables downsizing towards the target size.
   *
   */
  "isDownsizeEnabled"?: boolean;
  /**
   * The configured target size for the GPU Memory cluster.
   *  Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  "targetSize"?: number;
}

export namespace UpdateComputeGpuMemoryClusterScaleConfig {
  export function getJsonObj(obj: UpdateComputeGpuMemoryClusterScaleConfig): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: UpdateComputeGpuMemoryClusterScaleConfig): object {
    const jsonObj = { ...obj, ...{} };

    return jsonObj;
  }
}
