/**
 * Batch API
 * Use the Batch Control Plane API to encapsulate and manage all aspects of computationally intensive jobs.
 * OpenAPI spec version: 20251031
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Extended information for the CPU-specific task profile.
 */
export interface CpuShapeTaskProfileExtendedInformation
  extends model.BatchTaskProfileExtendedInformation {
  /**
   * A name of the CPU shape.
   */
  "shapeName": string;

  "type": string;
}

export namespace CpuShapeTaskProfileExtendedInformation {
  export function getJsonObj(
    obj: CpuShapeTaskProfileExtendedInformation,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.BatchTaskProfileExtendedInformation.getJsonObj(
            obj
          ) as CpuShapeTaskProfileExtendedInformation)),
      ...{}
    };

    return jsonObj;
  }
  export const type = "CPU_SHAPE_TASK_PROFILE_EXTENDED_INFORMATION";
  export function getDeserializedJsonObj(
    obj: CpuShapeTaskProfileExtendedInformation,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj
        ? obj
        : (model.BatchTaskProfileExtendedInformation.getDeserializedJsonObj(
            obj
          ) as CpuShapeTaskProfileExtendedInformation)),
      ...{}
    };

    return jsonObj;
  }
}
