/**
 * Batch API
 * Use the Batch Control Plane API to encapsulate and manage all aspects of computationally intensive jobs.
 * OpenAPI spec version: 20251031
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2025, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * The data to create a batch job.
 * If the value for a collection is absent or is explicitly provided as null, it will be converted to an empty value, i.e. \"[]\" or \"{}\" in json notation. This applies to nested collections as well.
 *
 */
export interface CreateBatchJobDetails {
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
   */
  "compartmentId": string;
  /**
   * The [OCID](https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent batch job pool.
   */
  "batchJobPoolId": string;
  /**
   * A user-friendly name. Does not have to be unique, and it's changeable.
   * If not specified or provided as null or empty string, it will be generated as \"<resourceType><timeCreated>\", where timeCreated corresponds with the resource creation time in ISO 8601 basic format, i.e. omitting separating punctuation, at second-level precision and no UTC offset. Example: batchjob20250914115623.
   *
   */
  "displayName"?: string;
  /**
   * An optional description that provides additional context next to the displayName.
   */
  "description"?: string;
  /**
   * An environment variables to use for the job's tasks (can be overridden by task's environment variables).
   */
  "environmentVariables"?: Array<model.EnvironmentVariable>;
  /**
   * A list of tasks to be executed within this job.
   * Maximum number of tasks a job can have in total, across all nested levels, is 1000.
   *
   */
  "tasks": Array<model.CreateBatchTaskDetails>;
  /**
    * Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
* For more information, see [Resource Tags](https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
* <p>
Example: {@code {\"Department\": \"Finance\"}}
* 
    */
  "freeformTags"?: { [key: string]: string };
  /**
    * Defined tags for this resource. Each key is predefined and scoped to a namespace.
* For more information, see [Resource Tags](https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
* <p>
Example: {@code {\"Operations\": {\"CostCenter\": \"42\"}}}
* 
    */
  "definedTags"?: { [key: string]: { [key: string]: any } };
}

export namespace CreateBatchJobDetails {
  export function getJsonObj(obj: CreateBatchJobDetails): object {
    const jsonObj = {
      ...obj,
      ...{
        "environmentVariables": obj.environmentVariables
          ? obj.environmentVariables.map(item => {
              return model.EnvironmentVariable.getJsonObj(item);
            })
          : undefined,
        "tasks": obj.tasks
          ? obj.tasks.map(item => {
              return model.CreateBatchTaskDetails.getJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
  export function getDeserializedJsonObj(obj: CreateBatchJobDetails): object {
    const jsonObj = {
      ...obj,
      ...{
        "environmentVariables": obj.environmentVariables
          ? obj.environmentVariables.map(item => {
              return model.EnvironmentVariable.getDeserializedJsonObj(item);
            })
          : undefined,
        "tasks": obj.tasks
          ? obj.tasks.map(item => {
              return model.CreateBatchTaskDetails.getDeserializedJsonObj(item);
            })
          : undefined
      }
    };

    return jsonObj;
  }
}
