/**
 * Container Instance API
 * A description of the Container Instance API
 * OpenAPI spec version: 20210415
 *
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from "../model";
import common = require("oci-common");

/**
 * Type of a Linux fsGroupChangePolicy.
 **/
export enum ContainerFsGroupChangePolicyType {
  Always = "ALWAYS",
  OnRootMismatch = "ON_ROOT_MISMATCH",

  /**
   * This value is used if a service returns a value for this enum that is not recognized by this
   * version of the SDK.
   */
  UnknownValue = "UNKNOWN_VALUE"
}

export namespace ContainerFsGroupChangePolicyType {
  export function getJsonObj(
    obj: ContainerFsGroupChangePolicyType
  ): ContainerFsGroupChangePolicyType {
    return obj;
  }
  export function getDeserializedJsonObj(
    obj: ContainerFsGroupChangePolicyType
  ): ContainerFsGroupChangePolicyType {
    return obj;
  }
}
